<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EarthquakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarthquakeRepository extends EntityRepository
{
    /**
     * Get Earthquakes by given date time
     * 
     * @param  DateTime $start
     * @param  DateTime $end
     * @return array
     */
    public function getEarthQuakeByInterval(\DateTime $start, \DateTime $end)
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->where($qb->expr()->between('e.date', ':start', ':end'))
            ->setParameters(array(
                'start' => $start,
                'end' => $end
            ))
        ;
        return $qb->getQuery()->getResult();
    }
    
    /**
     * Get Earthquakes nearest by coordenades
     * 
     * @param  Float $lat
     * @param  Float $lon
     * @return array
     */
    public function getEarthQuakeNearest($lat, $lon){
        
        $em = $this->getDoctrine()->getManager();
 
        $query = $em->createQuery(
            'SELECT *
            FROM AppBundle:Earthquake ea
            WHERE earth_box( ll_to_earth(:current_user_lat, :current_user_lng), :radius_in_metres) @> ll_to_earth(ea.lat, ea.lon);'
         )->setParameter('current_user_lat', $lat)
         ->setParameter('current_user_lng', $lon)
         ->setParameter('radius_in_metres', 100000);
        
        return $query->getResult();
        
    }
}
